<?php

// Generated by ZF2's ./bin/classmap_generator.php
return [
    'PhlyContact\Service\ContactControllerFactory'    => __DIR__ . '/src/PhlyContact/Service/ContactControllerFactory.php',
    'PhlyContact\Service\ContactCaptchaFactory'       => __DIR__ . '/src/PhlyContact/Service/ContactCaptchaFactory.php',
    'PhlyContact\Service\ContactFormFactory'          => __DIR__ . '/src/PhlyContact/Service/ContactFormFactory.php',
    'PhlyContact\Service\ContactMailTransportFactory' => __DIR__ . '/src/PhlyContact/Service/ContactMailTransportFactory.php',
    'PhlyContact\Service\ContactMailMessageFactory'   => __DIR__ . '/src/PhlyContact/Service/ContactMailMessageFactory.php',
    'PhlyContact\Controller\ContactController'        => __DIR__ . '/src/PhlyContact/Controller/ContactController.php',
    'PhlyContact\Form\ContactFilter'                  => __DIR__ . '/src/PhlyContact/Form/ContactFilter.php',
    'PhlyContact\Form\ContactForm'                    => __DIR__ . '/src/PhlyContact/Form/ContactForm.php',
];
